stages:
  - test
  - build

variables:
  RUST_BACKTRACE: "1"

test:
  stage: test
  image: rust:1.80
  script:
    - cargo test

build:
  stage: build
  image: rust:1.80
  script:
   - cargo build --release
